### PR TITLE
accelerator's are not blalck anymore

### PR DESCRIPTION
**Pull request by Yanpas**
Before on the right, now on the left.

### CODE REVIEW

**Comment by clefebvre** [comment]
I know this is subjective and the change is probably coming from GTK upstream, but I actually quite prefer the way it is now.. with grey rather than black.

**Comment by JosephMcc** [comment]
I'm with clem on this. I prefer the way it is now.

Even if this doesn't get merged could I make a suggestion for future PR's? When you add a second commit to fix something from the first like you did here, could you just squash those down into one commit?

**Comment by Yanpas** [comment]
Ok, I ll squash. Github supports automatic squashing before merging. 
@clefebvre the point is that now the behavior is inconsistent: in gtk2 apps accelerators are grey, in gtk3 are black. After this commit accelerators will be grey in both

**Comment by JosephMcc** [comment]
The inconsistency is a fair point. I would prefer to see it go the other way though. Make the gtk2 ones darker. Don't remember how much flexibility you have there though.

**Comment by clefebvre** [comment]
Oh.. sorry, I misread this then. I thought you were changing grey -> black :)

I tested this with Mint-Y initially and they were already grey (in GTK3) there, so I got confused.

**Comment by Yanpas** [comment]
Is this commit ready for merge?
View https://github.com/linuxmint/mint-x-icons/pull/151 also please

**Comment by clefebvre** [comment]
Hi @Yanpas, sorry about the delay. I'll tackle this today.

**Pull request merged**
